services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 8082:8082
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    expose:
      - 8080
    networks:
      - local-ai_demo
      - evolution-net
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5434/evolution

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres-evo
    image: postgres:16-alpine
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGPORT=5434
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5434

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  local-ai_demo:
    name: local-ai_demo
    external: true
  evolution-net:
    name: evolution-net
    driver: bridge
